server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mariadb://localhost:3306/authentication_service?createIfNotExists=true # Thay đổi JDBC URL cho MariaDB
    username: root  # Thay đổi tên người dùng của bạn
    password: 123456  # Thay đổi mật khẩu của bạn
    driver-class-name: org.mariadb.jdbc.Driver  # Sử dụng driver class cho MariaDB

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect  # Sử dụng dialect cho MariaDB
#    database: mariadb  # Đặt loại cơ sở dữ liệu là MariaDB








